const _optionsList = [
  'Travel',
  'Mystery',
  'Historical Fiction',
  'Sequential Art',
  'Classics',
  'Philosophy',
  'Romance',
  'Womens Fiction',
  'Fiction',
  'Childrens',
  'Religion',
  'Nonfiction',
  'Music',
  'Default',
  'Science Fiction',
  'Sports and Games',
  'Add a comment',
  'Fantasy',
  'New Adult',
  'Young Adult',
  'Science',
  'Poetry',
  'Paranormal',
  'Art',
  'Psychology',
  'Autobiography',
  'Parenting',
  'Adult Fiction',
  'Humor',
  'Horror',
  'History',
  'Food and Drink',
  'Christian Fiction',
  'Business',
  'Biography',
  'Thriller',
  'Contemporary',
  'Spirituality',
  'Academic',
  'Self Help',
  'Historical',
  'Christian',
  'Suspense',
  'Short Stories',
  'Novels',
  'Health',
  'Politics',
  'Cultural',
  'Erotica',
  'Crime'
] as const;

type optionT = (typeof _optionsList)[number];
export type optionsArrayT = optionT[];

export const optionsList: optionsArrayT = _optionsList
  .slice(0)
  .sort((a, b) => a.localeCompare(b));
